### ISSUE TITLE
[Idea] Allow multiple profiles to be applied to a cluster.

### ISSUE THREAD

**Issue by cre8minus1** [arlonproj/arlon#119]
**Is your feature request related to a problem? Please describe.**
Users may want to have more than one profile, today this is not supported

**Describe the solution you'd like**
Users should be able to layer/connect many profiles, for example
 * Platform Apps Profile
 * Security Profile 
 * Developer Apps 

**Describe alternatives you've considered**
There are not any alternates outside of adding more to an existing profile

Aha! Link: https://pf9.aha.io/features/ARLON-255

**Comment by cruizen** [comment]
@bcle can confirm - that this is already supported with the next-gen (gen2) profiles.

**Comment by cruizen** [comment]
Hi @bcle , can we close this issue?

**Comment by bcle** [comment]
Yes, done in v0.10
