### ISSUE TITLE
Install CAPI in the management cluster

### ISSUE THREAD

**Issue by ShaunakJoshi1407** [arlonproj/arlon#145]

**Comment by Rohitrajak1807** [comment]
@ShaunakJoshi1407 can we assume that the management cluster is up and running and that `$KUBECONFIG` is pointing to the correct file?

**Comment by ShaunakJoshi1407** [comment]
Currently as a part of verify, the user is only giving the` kubeconfigPath`(kubeconfig location/file) as a parameter and then we verify if this kubeconfig has correct access and is working fine. In addition to this, we can also set `$KUBECONFIG` to this value just to be sure.
