### ISSUE TITLE
CAPI cluster autoscaler support (for MachineDeployment) for next-gen clusters

### ISSUE THREAD

**Issue by bcle** [arlonproj/arlon#156]
CAS is supported for current-gen clusters via flags and the Helm chart which provisions CallHomeConfig resource if needed. This is for porting that work to next-gen clusters.

Note that this only works with MachinePool / AWSMachinePool based CAPI clusters.

Aha! Link: https://pf9.aha.io/features/ARLON-268

**Comment by cruizen** [comment]
@bcle  So, CAS is supported already/ OOTB with MachinePool / AWSMachinePool based CAPI clusters - but not for MachineDeployment - and this task is about adding support for MachineDeployment? 

Prerequisite for this task: We need to confirm the ability to create MachinePool / AWSMachinePool based (CAPI) EKS clusters first.

**Comment by bcle** [comment]
Actually, the situation is more dire than that.
- There is no Cluster Autoscaler support for MachinePool with either AWSMachine or AWSManagedMachinePool. This is a CAPI problem. For more info: https://platform9.slack.com/archives/C02JC5RAC3Y/p1663904783947039?thread_ts=1663895938.989799&cid=C02JC5RAC3Y
- The CAPI specific CAS works with MachineDeployment. But for that to work, Arlon needs to configure the management cluster a certain way. This used to work until it broke with the service token changes in k8s 1.21+.
