### ISSUE TITLE
An "init" command to integrate Arlon with ArgoCD, and optionally create a "starter kit" of example bundles, profiles, clusterspecs, baseclusters?

### ISSUE THREAD

**Issue by bcle** [arlonproj/arlon#223]
Arlon setup is still very complex, in particular in these areas:
- Authentication integration with argocd
- The need to create a bunch of bundles, profiles, clusterspecs, base clusters (when using next-gen clusters) before anything useful can be done

Aha! Link: https://pf9.aha.io/features/ARLON-298
Subtasks:
- [x] #295
- [x] #298
- [x] #302
- [x] #318

**Comment by Rohitrajak1807** [comment]
@bcle is this the same as doing these steps from Arlon installation:
> Follow steps 1-4 of the [ArgoCD installation guide](https://argo-cd.readthedocs.io/en/stable/getting_started/) to install ?
> ArgoCD onto your management cluster. After this step, you should be logged in as admin and a config file was created at > ${HOME}/.config/argocd/config
> Create your workspace repository in your git provider if necessary, then register it. Example: argocd repo add 
> https://github.com/myname/arlon_workspace --username myname --password secret.
> Note: type argocd repo add --help to see all available options.
> For Arlon developers, this is not your fork of the Arlon source code repository, but a separate git repo where some artifacts like profiles created by Arlon will be stored.
> Highly recommended: [configure a webhook](https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/) to immediately notify ArgoCD of changes to the repo. This will be especially useful during the tutorial. Without a webhook, repo changes may take up to 3 minutes to be detected, delaying cluster configuration updates.
> [Create a local user](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/) named arlon with the apiKey capability. This involves editing the argocd-cm ConfigMap using kubectl.
> Adjust the RBAC settings to grant admin permissions to the arlon user. This involves editing the argocd-rbac-cm 
> ConfigMap to add the entry g, arlon, role:admin under the policy.csv section. Example:
> apiVersion: v1
> data:
>  policy.csv: |
>     g, arlon, role:admin
> kind: ConfigMap
> [...]
> Generate an account token: argocd account generate-token --account arlon
> Make a temporary copy of the config file: cp ${HOME}/.config/argocd/config /tmp/config then edit it to replace the value of auth-token with the token from the previous step. Save changes. This file will be used to configure the Arlon controller's ArgoCD credentials during the next steps.

**Comment by bcle** [comment]
Yes, more or less. We need some form of quick start. Some steps could be made optional, depending on what the user already has. For e.g. if they already have ArgoCD in the management cluster, then integrate with it. Otherwise, offer to install it, similar to the testbed script.

**Comment by Rohitrajak1807** [comment]
Integrating arlon with argocd seems to be quite involved and has many steps. Readjusting estimate to size Large.

**Comment by Rohitrajak1807** [comment]
@bcle when you say:
>  ... create a "starter kit" of example bundles, profiles, clusterspecs, baseclusters?
Do you mean just push dummy basecluster manifests?
