### ISSUE TITLE
autogenerate cluster name related parameters / helm values for bundles

### ISSUE THREAD

**Issue by bcle** [arlonproj/arlon#27]
Use case: the AWS cluster autoscaler YAML template used by Platform9 has some fields that are parameterized based on a unique "cluster UUID". Arlon does not use the concept of cluster UUIDs but it does assume (and verify) that cluster names are unique (within the `arlon` namespace in the mangement cluster). So it could automatically insert Helm values into the app representing the bundle. If the bundle happens to be a Helm chart, it could take advantage of that. If the bundle is (or references) a Kustomize template, then investigate generating the right Kustomization.

**Comment by cre8minus1** [comment]
@bcle is this required for 0.9.0

**Comment by bcle** [comment]
Solved. Arlon does not use PMK's cluster autoscaler manifests. It uses its own, derived from the upstream ones, and it's designed for the CAPI provider for CAS, not the traditional AWS ASG provider. So there is no need for ClusterUUID.
