### ISSUE TITLE
Optionally, add example bundles, profiles and basecluster manifests

### ISSUE THREAD

**Issue by Rohitrajak1807** [arlonproj/arlon#298]
Subtasks:
- [x] #309
- [x] #308

**Comment by Rohitrajak1807** [comment]
Profiles and bundles are undergoing changes. Seeing that, the work on creating example bundle and profiles has been frozen until those changes are in.

**Comment by cruizen** [comment]
We will continue with task once the profiles re-design is done - to avoid rework. cc: @bcle , @Rohitrajak1807

**Comment by Rohitrajak1807** [comment]
@cruizen, @bcle adding bootstrap steps for CAPI providers will need some refactoring for supporting multiple providers(whenever we do). Depending on that we might have to re-estimate this task as well. Will keep everyone posted.
