### ISSUE TITLE
Docs: Update design.md and tutorial.md to be consistent about gen1/ gen 2 clusters and profiles

### ISSUE THREAD

**Issue by cruizen** [arlonproj/arlon#311]
Should this be called Clusterspec too , for consistency with the remaining docs ?

_Originally posted by @ShaunakJoshi1407 in https://github.com/arlonproj/arlon/pull/297#discussion_r1024164429_

**Comment by ShaunakJoshi1407** [comment]
As a part of this task, I will also add a tutorial for gen-2 clusters
