### ISSUE TITLE
Fix e2e tests with AWSMachinePool and AWSManagedMachinePool components

### ISSUE THREAD

**Issue by ShaunakJoshi1407** [arlonproj/arlon#343]
- The e2e tests with AWSManagedMachinePool and AWSMachinePool are failing with these errors : 

`failed to create nodegroup: failed to create nodegroup: InvalidParameterException: The provided role doesn't have the Amazon EKS Managed Policies associated with it. Please ensure the following policies [arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy, arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly] are attached`

`message: "failed to create AWSMachinePool: failed to create autoscaling group:
        +      ValidationError: The security group 'sg-0cdf322997dfd1e5b' does not exist\n\tstatus
        +      code: 400, request id: 67443c95-ab29-4968-bc27-b2a5f4caf602"
        +    reason: ASGProvisionFailed
        +    severity: Error
        +    status: "False"
        +    type: Ready
`     
https://github.com/arlonproj/arlon/actions/runs/3601627211

- The CFT stack that we are using to run these tests is the same stack that is being used internally for integration tests and builds. As our e2e test failures shouldn’t affect this stack and in turn the builds, we have decided to switch to a new CFT stack

Aha! Link: https://pf9.aha.io/features/ARLON-382

**Comment by ShaunakJoshi1407** [comment]
I have been testing the AWSMachinePool and AWSManagedMachinePool changes with a new stack and for these tests, all the components except MachineDeployment are Ready and Healthy. MachineDeployment is stuck in a ScalingUp state although both the machines required are provisioned and ready. This issue has been communicated to the cluster-api-aws official channel for resolution : https://kubernetes.slack.com/archives/CD6U2V71N/p1671189094523659

**Comment by cruizen** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Arlon-Team-6345a9610e79cb1603a53d69/issues/arlonproj/arlon/343?planning-poker) with Zenhub @bcle @jayanth-tjvrr @Rohitrajak1807 @ShaunakJoshi1407
