### ISSUE TITLE
Create a separate documentation for v0.9 and v0.10

### ISSUE THREAD

**Issue by ShaunakJoshi1407** [arlonproj/arlon#349]
There are some differences between v0.9 and v0.10 and the docs also need to be different for that purpose.

- [x] https://github.com/arlonproj/arlon/issues/361
- [x] https://github.com/arlonproj/arlon/issues/213

**Comment by cruizen** [comment]
This is to update the docs content for tutorial, base clusters/ cluster specs etc so that each branch has docs to reflect what is developed/ available with the corresponding release.

**Comment by ShaunakJoshi1407** [comment]
@Rohitrajak1807 can you close this out, when the `arlon init` doc changes go in ?
