### ISSUE TITLE
argocd auth token has expired message appears even after logging in to argocd

### ISSUE THREAD

**Issue by jayanth-tjvrr** [arlonproj/arlon#353]
Even after I login into argocd, below message still appears when I run any cluster commands. But all the argocd commands are working fine.

<img width="497" alt="image" src="https://user-images.githubusercontent.com/65030629/206444845-27dd1bdb-917f-43d7-bd98-ecb215456dc4.png">

**Comment by ShaunakJoshi1407** [comment]
I am not able to reproduce this on my setup so far. Moving out of from 0.10 as it is not reproducible

**Comment by cruizen** [comment]
Let's try to reproduce this - else we can close it and reopen if we encounter it again.

**Comment by ShaunakJoshi1407** [comment]
Still not able to reproduce this issue. Let’s reopen this if we encounter this again
