### ISSUE TITLE
Bootstrap: Add `install` or `verify` CLI commands to ensure, arlon, ArgoCD and ClusterAPI (and maybe Crossplane) are correctly installed/configured

### ISSUE THREAD

**Issue by bcle** [arlonproj/arlon#4]
To simplify setting up Arlon we should have a bootstrap command that installs Arlon, ArgoCD and ClusterAPI into a users cluster. 
Bootstrap should also handle clusters that already have ArgoCD, CAPI or both installed. 

 (We need to decide if installing CAPI Cloud Providers should be part of this)

Currently this task is subdivided into two seperate tasks for `verify` and `install `
- [x] https://github.com/arlonproj/arlon/issues/143
- [x] https://github.com/arlonproj/arlon/issues/144
Aha! Link: https://pf9.aha.io/features/ARLON-173

**Comment by cruizen** [comment]
- [ ] verify 
- [ ] install
