### ISSUE TITLE
cluster overrides are not declarative

### ISSUE THREAD

**Issue by bcle** [arlonproj/arlon#416]
The "cluster overrides" feature introduced in v0.10 creates files in git and is not declarative because
- Creating the override requires the `arlon` CLI/API
- Deleting the override (and the cluster) also requires `arlon` CLI/API
This is inconsistent with the fully declarative gen2 clusters (with no overrides) and AppProfiles.
One consequence of this flaw is the overrides feature cannot be added to the `examples/declarative` example.

Aha! Link: https://pf9.aha.io/features/ARLON-376

**Comment by bcle** [comment]
This work probably involves adding:
- A new custom resource for Cluster
- A new controller. It will be responsible for:
   - creating and cleaning up the git files (if overrides are used)
   - creating and cleaning up the ArgoCD applications representing the cluster
The effort required is thus in the same ballpark as gen2 profiles (AppProfiles). That took ~2 months, but was subject to multiple team feedback and redesign cycles. Hopefully things will go smoother with this one, so my current (optimistic) estimate is ~1 month.

**Comment by cruizen** [comment]
Hi @bcle , can we add this to a sprint (depending on the start date) - so that we can plan other tasks accordingly?

**Comment by bcle** [comment]
Yes absolutely

**Comment by cruizen** [comment]
> Yes absolutely

Thanks, assigned it to the next sprint that begins next Monday.
