### ISSUE TITLE
[Idea] Add golang CI lint GitHub Action for Arlon

### ISSUE THREAD

**Issue by Rohitrajak1807** [arlonproj/arlon#432]
Golang CI lint detects common code problems and can be helpful in improving code quality of the project

**Comment by cruizen** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Arlon-Team-6345a9610e79cb1603a53d69/issues/arlonproj/arlon/432?planning-poker) with Zenhub @bcle @jayanth-tjvrr @Rohitrajak1807 @ShaunakJoshi1407

**Comment by cruizen** [comment]
We can enable the GitHub action in a branch and fix the code issues in that branch first. There were some 50+ violations last I checked.

**Comment by cruizen** [comment]
@arlonproj/arlon-dev Like @Rohitrajak1807 suggested, it's a good idea to run `golangci-lint` locally until then and fix trivial issues that it finds before we have a CI action available.
