### ISSUE TITLE
Arlon Create Cluster Command

### ISSUE THREAD

**Issue by cre8minus1** [arlonproj/arlon#51]
As a user of Arlon I would like the CLI to allow cluster creation based on three inputs: 
1.  ClusterSpec,
2.  Profile, and
3. Git repository 

The create cluster command will read the ClusterSpec from the Git repo that Arlon is configured to work with, read the Profile from where Arlon is configured to work with and then write the new clusters configuration to the Git Repository specified. 
This will mean that each cluster has a distinct structure in Git, that is separate to the Git Repository where each ClusterSpec and Profile is stored. 

The create command will also interact with ArgoCD APIs and create the related application objects for the Cluster and Profile.

**Comment by bcle** [comment]
For 0.3.x the command is called `arlon cluster deploy`
