### ISSUE TITLE
Linked Mode Clusters

### ISSUE THREAD

**Issue by cre8minus1** [arlonproj/arlon#53]
Arlon is built to simplify running clusters at scale using objects stored in Git and reconcile using ArgoCD. There are multiple ways that this can be achieved, for example, each cluster could have its own unique set of files in a defined Git hierarchy. Or, a set of clusters could all leverage a single set of fines in a defined hierarchy. Or a blend of Both. 

Linked Mode is an approach that builds clusters from a central group of files that are shared. 
Clusters are created from a ClusterSpec and Profile, users invoke `Arlon cluster create linked <cluster_name> <cluster_spec> <profile>`  - This will deploy the cluster directly linking the clusters to the objects stored in Git. 

This means  any change to the ClusterSpec, profile or bundles in Git would reflect as a change in any/all cluster running off of the same ClusterSpec. 

This is the default behavior of Arlon.

[Read More Here](https://github.com/arlonproj/arlon/wiki/%5BFeature%5D-Linked-Mode)

BACKGROUND

The end to end profile flow:

* Create CAPI YAML in Git -  
* Create Apps & K8s Resources in git-
* Create a ClusterSpec, Bundles and a Profile from each object 

Arlon creates cluster from profile and the clusterSpec.  

Register the cluster into Argo (For the Apps and objects in the profile to deploy something needs to Automatically register the cluster into CAPI )  

Once registered the Apps and K8s objects deploy, App for all other objects

Aha! Link: https://pf9.aha.io/features/ARLON-163

**Comment by cre8minus1** [comment]
@bcle are you going to put an estimate on this or are you treating it as a overarching issues? like an epic?

**Comment by bcle** [comment]
Yeah it's more like an epic.

**Comment by cruizen** [comment]
Hi @bcle , @cre8minus1  I understand this task at a high level but looks tough to estimate as an aggregate. It looks like we will need to break it down into multiple smaller tasks that can be estimated separately?

**Comment by bcle** [comment]
Linked mode just means shared update, which you get out-of-the-box with baseclusters.
