### ISSUE TITLE
AWS ClusterSpec -  Full ClusterAPI support. 

### ISSUE THREAD

**Issue by cre8minus1** [arlonproj/arlon#55]
As user of Kubernetes in AWS it would great to see support for clusterSpecs that incorporated more of the complete clusterAPI specifications. The clusterSpec should be stored in Git and support all clusterAPI CRDs including elements such as.

* Region
* VPC
* Domain
* Instance Types
* Add-ons
* Autoscaling Config
* nodepools/ machine sets 
* SSH keys 
* Control plane types (EKS or Unmanaged)

Aha! Link: https://pf9.aha.io/features/ARLON-161

**Comment by cruizen** [comment]
Should this issue be resolved now that we have `baseclusters` in Arlon 0.9 for full CAPI support? cc: @bcle , @cre8minus1

**Comment by bcle** [comment]
Yes, thanks. Closing.
