### ISSUE TITLE
Create Compiled Arlon CLI for Linux and the Build Infrastructure 

### ISSUE THREAD

**Issue by cre8minus1** [arlonproj/arlon#60]
To make Arlon easier to use we need to create an automated build system that can publish the cli for  Linux. 

The end goal is to make using Arlon much easier, with a complied CLI users can download and go. 
Users of any desktop OS should be able to download the CLI and use it. 

 - [ ] Allow users to install using APT

Other OS support will be delivered after Linux
 - MACOS Allow users to install using brew #114 
 - Windows OS  Investigate using https://chocolatey.org for Windows #115

Aha! Link: https://pf9.aha.io/features/ARLON-156

**Comment by bcle** [comment]
It may be easier to just publish binaries without package system integration. The only downside with that is it won't have a built-in upgrade feature.

**Comment by bcle** [comment]
I just noticed that issue #61 is about a self-update system. Perhaps a standalone binary combined with that feature would solve the lack of integration with native package manager.

**Comment by cruizen** [comment]
I can look into this (tagging and releasing binaries). 
In addition, [GoReleaser](https://goreleaser.com/) has support for

**Comment by bcle** [comment]
@cruizen can you adjust the effort estimate, and also break this into estimates for each of the OSes.
