### ISSUE TITLE
Arlon CLI new version check

### ISSUE THREAD

**Issue by cre8minus1** [arlonproj/arlon#61]
The Arlon CLI needs to check for new versions and notify users to upgrade. 
This could also be automatic, however this will require all changes to not be breaking changes. 

At a minimum users should be able to run `arlon version` and see their current version 
 * Upgrade to be handled separately with `arlon update` to upgrade. https://github.com/arlonproj/arlon/issues/254
The version command should return the current version and if a new version is available.

Aha! Link: https://pf9.aha.io/features/ARLON-155

**Comment by Rohitrajak1807** [comment]
> This could also be automatic, however this will require all changes to not be breaking changes.

This requirement will need some thought.

**Comment by cruizen** [comment]
Deferring to sprint 9

**Comment by cruizen** [comment]
If a user is on v0.3.5, the output of `arlon version` will be like : `Arlon v0.3.5 \n Arlon is outdated. A new version v0.3.7 is available. Please update Arlon` ....
If a user is on v0.9.1, the output of `arlon version` will be like : `Arlon v0.9.1 \n Arlon is outdated. A new version v0.9.12 is available. Please update Arlon` ....
