### ISSUE TITLE
Arlon CLI- Register/unregister Git 

### ISSUE THREAD

**Issue by cre8minus1** [arlonproj/arlon#70]
As a user of Arlon I would like the CLI to have a dedicated command for registering and unregistering the Git repo where my Profiles will be written.

So that I do not need to manually place the Profile and Git and manually generate the path that Arlon will use during the `cluster deploy` command.

It would also be good if I could specify which repository should be used for deploying clusters and their related ArgoCD elements (workspace repository) versus which repositories are used for storing the Bundle, Profile and ClusterSpec data. 
This is especially important when we start supporting #54 Cloned Clusters as the entire contents stored in Git will be duplicated.

Aha! Link: https://pf9.aha.io/features/ARLON-146

**Comment by cre8minus1** [comment]
We need to make it very clear how Git Authentication and authorization is handled. right now its not clear.

**Comment by cruizen** [comment]
Aren't we planning to get rid of the git workspace repository in 0.9? cc: @bcle

**Comment by bcle** [comment]
According to the recent replanning, the current plan for 0.9.x is to use next-gen clusters with current-gen profiles. So the user still needs to supply a repo for storing dynamic profiles. Also, the base cluster itself needs to be in a repo that arlon can read/write (for the prep phase).

**Comment by cruizen** [comment]
> We need to make it very clear how Git Authentication and authorization is handled. right now its not clear.
Currently, the readme asks to set environment variables for $WORKSPACE_REPO and $ARLON_REPO and set these to the paths where these repositories have been checked out.

**Comment by ShaunakJoshi1407** [comment]
I just wanted to add that we were thinking of using this to verify the user permissions for a particular repo: We were thinking of using this : https://docs.github.com/en/rest/collaborators/collaborators#get-repository-permissions-for-a-user
